dbt_example:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: athena-465119
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_dw') }}"
      threads: 4
      keyfile: /root/.dbt/athena-465119-b5e86ed4cb74.json